name: Python Unit Tests

on:
  push:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  Python-Unit-Test:
    name: Python Unit Tests
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.6]
        platform: [ubuntu-18.04]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip
        make libpecos VFLAG=-v
    - name: Test with pytest
      run: |
        pip install -U pytest
        pip install pytest-cov
        pytest -rP test/pecos/ann/test_hnsw.py
